### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by mohayl** [HPI-Information-Systems/TimeEval#28]
statsmodels and pip

**Comment by CodeLionX** [comment]
Dear @mohayl,

We can't reproduce your problem, but we think that you might use an incompatible Python-version. TimeEval supports all Python versions >= 3.7 and <= 3.9. **Python 3.10 is not supported** right now.

Please specify your environment (OS, python version, pip version, if you use conda or virtualenv, ...) and the steps you tried to install TimeEval so that we can reproduce your issue.

**Comment by wenig** [comment]
We updated the supported Python versions (https://github.com/HPI-Information-Systems/TimeEval/pull/29).

@mohayl If the dependency conflict still remains, please open another issue!
